name: ml-hol
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.20.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - scikit-learn>=1.0.0
  - pandas>=1.3.0
  - tensorflow>=2.8.0
  - jupyterlab>=3.0.0
  - notebook>=6.0.0
  - ipywidgets>=7.0.0
  - pip:
    - japanize-matplotlib>=1.1.0